name: Build APK
on: workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Unzip project
      run: |
        unzip InventoryLite_Fixed.zip -d .
    - uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: '17'
    - uses: android-actions/setup-android@v3
    - name: Install SDK packages
      run: |
        yes | sdkmanager --licenses
        sdkmanager "platform-tools" "platforms;android-34" "build-tools;34.0.0"
    - name: Generate Gradle wrapper
      uses: gradle/gradle-build-action@v3
      with:
        gradle-version: 8.6
        build-root-directory: InventoryLiteFixed
        arguments: wrapper
    - name: Build debug APK
      uses: gradle/gradle-build-action@v3
      with:
        build-root-directory: InventoryLiteFixed
        arguments: assembleDebug
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: app-debug
        path: InventoryLiteFixed/app/build/outputs/apk/debug/app-debug.apk
